### PR TITLE
Package name change + Facebook login

### PR DESCRIPTION
**Pull request by TheFlash98**
changing the package names from `com.sarthak......` to `com.iitb.ferozepurwaale.lendit_app`

### CODE REVIEW

**Comment by CodeMaxx** [comment]
Nice progress

**Comment by TheFlash98** [comment]
I've been trying to finish the Facebook login but am facing some issues. Will send another PR soon.

**Comment by CodeMaxx** [comment]
Awesome! Write in the doc or something what data you'll be fetching from facebook. We'll create the backend table accordingly.

**Comment by TheFlash98** [comment]
Sure. Will do that as soon as I'm done.

**Comment by TheFlash98** [comment]
Facebook login gives you all this:
https://developers.facebook.com/docs/facebook-login/overview

**Comment by arpan98** [comment]
It works!

**Pull request merged**
